name: Add file to all repos

description: |
  This action creates a pull request adding a certain file to all repositories in an organization.

inputs:
  organization-name:
    description: 'The name of the organization.'
    required: true
  extensions:
    description: 'A list of recommended extensions to add to the .vscode/extensions.json file.'
    required: false
    default: '[]'
  repositories:
    description: 'A list of repositories to add the file to. If no repositories are specified, the file will be added to all repositories in the organization.'
    required: false
    default: ''
  only-if-extension-file-exists: 
    description: 'If true, the file will only be added if the .vscode/extensions.json file already exists.'
    required: false
    default: 'false'
  author-name:
    description: The author name. Use ${{ github.actor }} for user who triggered the workflow run.
    default: 'github-actions[bot]'
  author-email:
    description: The author email. Use ${{ github.actor }}@users.noreply.github.com for user who triggered the workflow run.
    default: 'github-actions[bot]@users.noreply.github.com' 
  pull-request-title: 
    description: 'The title of the pull request.'
    required: false
    default: 'Adding recommended extensions to vscode recommedations file'
  pull-request-body:
    description: 'The body of the pull request.'
    required: false
    default: |
      Adding recommended extensions to vscode recommedations file.
      This Pull Request is generated by a [GitHub Action](https://github.com/SvanBoxel/add-vscode-extension-action).
  commit-message:
    description: 'The commit message.'
    required: false
    default: 'Adding recommended extensions to vscode recommedations file'
  base: 
    description: 'The base branch to create the pull request against.'
    required: false
    default: 'main'
  branchname: 
    description: 'The name of the branch to create the pull request from.'
    required: false
    default: 'add-vscode-extension-action'
  github-token: 
    description: 'The GitHub token to use for authentication.'
    required: true

runs:
  using: "node16"
  main: "dist/index.js" 